language: java
dist: trusty
install: 
  - "cp .travis.settings.xml $HOME/.m2/settings.xml"
  - "mvn install -DskipTests=true -Dmaven.javadoc.skip=true --batch-mode --show-version"
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk11
  - openjdk8
